1. NumPy 배열 생성 및 연산
- NumPy를 사용해 3x3 정수 배열(1부터 9까지)과 2x5 실수 배열(0~1 사이 난수)을 생성하세요. 생성한 배열의 합계와 평균을 각각 계산하고, 두 배열을 곱한 결과를 출력하세요.
- - 배열의 형태를 유지하지 않아도 괜찮습니다.

2. Pandas를 활용한 데이터 처리
- 아래 데이터를 DataFrame으로 생성하세요.
Name: [Alice, Bob, None, Charlie]
Age: [25, None, 28, 35]
City: [New York, None, Chicago, None]

- 누락된 이름은 "Unknown"으로, 나이는 평균 나이로 채우고 수정된 DataFrame을 출력하세요.

3: HTTP 통신을 활용한 데이터 읽기 및 저장
- https://jsonplaceholder.typicode.com/todos 에서 JSON 데이터를 가져오세요.
데이터를 파일로 저장한 뒤, "title" 키의 값을 출력하세요.

제출 방식: 1, 2, 3을 콜랩 페이지 하나로 하여 링크 제출



In [31]:
import numpy as np

arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
print(f"합계 : {arr1.sum()} ")
print(f"평균 :  {arr1.mean()}")

arr2 = np.random.uniform(0, 1, size=(2,5))
print(arr2)
print(f"합계 : {arr2.sum()} ")
print(f"평균 :  {arr2.mean()}")

arr1_flat = arr1.flatten()
arr2_flat = arr2.flatten()[0:9]
print(f"곱셈 결과 : {arr1_flat * arr2_flat}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
합계 : 45 
평균 :  5.0
[[0.35011917 0.71010103 0.22124527 0.03885772 0.17865559]
 [0.39182295 0.84615593 0.81788038 0.07374502 0.29790133]]
합계 : 3.926484389681921 
평균 :  0.39264843896819207
곱셈 결과 : [0.35011917 1.42020206 0.6637358  0.15543087 0.89327796 2.35093772
 5.92309148 6.54304306 0.66370517]


In [32]:
import pandas as pd

data = {
    'Name' : ["Alice", "Bob", None, "Charlie"],
    'Age': [25, None, 28, 35],
    'City': ["New York", None, "Chicago", None]
}

data_pd = pd.DataFrame(data)
print(data_pd)

# 각각
# data_pd['Name'] = data_pd['Name'].fillna('Unknown')
# data_pd['City'] = data_pd['City'].fillna('Unknown')
# data_pd['Age'] = data_pd['Age'].fillna()

# 한번에
data_pd = data_pd.fillna({'Name': 'Unknown', 'Age': data_pd['Age'].mean().astype(int), 'City': 'Unknown'})
print(data_pd)

      Name   Age      City
0    Alice  25.0  New York
1      Bob   NaN      None
2     None  28.0   Chicago
3  Charlie  35.0      None
      Name   Age      City
0    Alice  25.0  New York
1      Bob  29.0   Unknown
2  Unknown  28.0   Chicago
3  Charlie  35.0   Unknown


In [ ]:
import requests
import json
import pandas as pd

response = requests.get('https://jsonplaceholder.typicode.com/todos')

with open('3주차과제_데이터.txt', 'w', encoding='utf-8') as f:
    f.write(response.text)

with open('3주차과제_데이터.txt', 'r', encoding='utf-8') as f:
    data = f.read()
    data_json = json.loads(data)
    df = pd.DataFrame(data_json)
    print(df['title'])

0                                     delectus aut autem
1                     quis ut nam facilis et officia qui
2                                    fugiat veniam minus
3                                       et porro tempora
4      laboriosam mollitia et enim quasi adipisci qui...
                             ...                        
195                  consequuntur aut ut fugit similique
196                    dignissimos quo nobis earum saepe
197                         quis eius est sint explicabo
198                         numquam repellendus a magnam
199                         ipsam aperiam voluptates qui
Name: title, Length: 200, dtype: object
